//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top2000.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSongs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSongs()
        {
            this.tblRanking = new HashSet<tblRanking>();
        }
    
        public int SongID { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public string SongName { get; set; }
        public Nullable<int> SongYear { get; set; }
    
        public virtual tblArtist tblArtist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRanking> tblRanking { get; set; }
    }
}
